name: CI Build

on:
    push:
        branches: '*'

jobs:
  perl-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - 'latest'
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: automatically building distribution file
        run: |
          perl Build.PL
          perl Build installdeps --cpan_client 'cpan -T'
          perl Build dist
      - uses: actions/upload-artifact@v2
        with:
           name: distribution
           path: ./*.gz
